# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='optimizer',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='optresult',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
