# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170821_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('eval_val', models.FloatField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('elapsed_time', models.FloatField()),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('file_path', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-registered_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='optimizer',
            options={'ordering': ['-registered_date']},
        ),
        migrations.AlterModelOptions(
            name='optresult',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='result',
            name='optimizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Optimizer'),
        ),
    ]
