# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170822_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optresult',
            name='optimizer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='solver',
            name='params',
        ),
        migrations.AlterField(
            model_name='result',
            name='optimizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Solver'),
        ),
        migrations.DeleteModel(
            name='Optimizer',
        ),
        migrations.DeleteModel(
            name='OptResult',
        ),
    ]
