# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170822_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='optimizer',
            new_name='solver',
        ),
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='elapsed_time',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='result',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solver',
            name='params',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solver',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='params',
            field=models.TextField(blank=True),
        ),
    ]
