# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170822_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='solver',
            name='file_path2',
            field=models.FilePathField(blank=True),
        ),
    ]
