# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170823_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solver',
            name='file_path2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
